### PR TITLE
Show error when trying to open a shared PDF without download permissions

### LINKED ISSUE #649: Disable pdf viewer on files that have download disabled
We should not attempt to open the pdf viewer for files that have download disabled as it fails to download the file from webdav

Ref https://github.com/nextcloud/server/pull/32482#issuecomment-1218387463

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #649

Although the best fix would be to fallback to Collabora if available currently [it does not seem to be possible to do that](https://github.com/nextcloud/files_pdfviewer/issues/649#issuecomment-1231326189), so for now just an error message is shown.

Also, while [it would be possible to use `this.$emit('error')` to notify the viewer that the file could not be loaded](https://github.com/nextcloud/viewer/issues/1440#issuecomment-1293510327) currently it does not seem possible to customize the message, so [the standard Viewer error](https://github.com/nextcloud/viewer/blob/c3e5c751b0decef5dbc103474208b6142f9deef9/src/components/Error.vue) with _Error loading {name of the file}_ would be shown. In this case it is worth explaning the reason, so the error is handled directly in the PDF viewer instead (but with the markup and style for the error element copied from the viewer). Maybe custom error messages will be possible in the future with the [Viewer 4.0 API](https://github.com/nextcloud/viewer/issues/2395) and then that code can go away :-)

Regarding the error message itself feel free to improve the wording :-) After several tries this is the best I could come up with :shrug:

Finally, note that before Nextcloud 28 when the PDF viewer was opened in public pages for a single share the UI was directly injected. When it was changed to use the viewer instead [a fallback to directly inject the UI was left just in case the viewer was not available](https://github.com/nextcloud/files_pdfviewer/pull/811/commits/809b65e9a6090acc71a044b00be602169f8d9961#diff-0053c45b7f561164925ff3568650a20e947493a5a84cd29ab3a6f6b66a6d9691R70-R79). This pull request only handles the disabled download permissions when the viewer is used, but not in the fallback case:
- The viewer already provides the needed file info, so handling the error without the viewer is more involved, as the file info would need to be fetched before loading the file in PDF.js, or a handler in PDF.js for loading errors would need to be used (which I have not found how :shrug: I am sure there is an easy way and I just simply missed it, but it is not worth spending more time on that due to the next point)
- In Nextcloud 31 `public.js` will go away (in another pull request) because it is no longer needed, so there will be no fallback at all. But also in Nextcloud 28 to 30 the fallback should never be used anyway; the viewer is expected to be always available, and if it is not or it did not properly load then something would need to be fixed, but keeping the fallback was just being overly cautious and it is not really needed.

## How to test

- Share a PDF file with another user
- Customize the share and disable `Allow download and sync`
- In a private window, log in as the other user
- Open the Files app
- Open the shared PDF

### Result with this pull request

image

### Result without this pull request

The PDF viewer is loaded, but contents are empty

### CODE REVIEW

File: src/views/PDFView.vue [hunk 1]
```diff
@@ -3,7 +3,13 @@
   - SPDX-License-Identifier: AGPL-3.0-or-later
   -->
 <template>
-	<iframe ref="iframe"
+	<div v-if="!isDownloadable"
+		id="emptycontent">
+		<div class="icon-error" />
+		<h2>{{ t('files_pdfviewer', 'To view a shared PDF file the sharer needs to allow downloads of the file') }}</h2>
```
Comment (Antreesy) [inline src/views/PDFView.vue:9]: `To view a shared PDF file, the owner must allow a download of the file` ?

There is also a case, when files_pdfviewer is not in the whitelist of Guests app, and guest account is trying to access it with 403. 
Possibly unrelated, but I could follow-up on top of that PR later

Comment (danxuliu) [reply src/views/PDFView.vue:9]: > `To view a shared PDF file, the owner must allow a download of the file` ?

Mmm, maybe the person should not be mentioned at all, because if a file is reshared and the owner disallows the download I guess (I have not checked) that it will be disallowed in the reshare, but if the owner allows it and the resharer disallows it then it would be also disallowed :thinking: 
 
> There is also a case, when files_pdfviewer is not in the whitelist of Guests app, and guest account is trying to access it with 403. Possibly unrelated, but I could follow-up on top of that PR later

Thanks, I was not aware of that. A follow up sounds good :-)

Comment (DanScharon) [reply src/views/PDFView.vue:9]: any news on the follow up?

**Comment by szaimen** [comment]
Hi @danxuliu, I wanted to test this. Unfortunately when I try to install the pdfviewer dependencies, I run into the following error:
image
I am not sure how to fix this unfortunately.

This should be easily reproducible with 
```
sudo docker run -it --rm \
--name nextcloud-easy-test \
-p 8443:443 \
-e SERVER_BRANCH=master \
-e PDFVIEWER_BRANCH=show-error-when-trying-to-open-a-shared-pdf-without-download-permissions \
-e VIEWER_BRANCH=master \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
ghcr.io/szaimen/nextcloud-easy-test:latest

```

**Comment by Antreesy** [comment]
> when I try to install the pdfviewer dependencies

Does it work with master/main branch of pdf_viewer? As there is only frontend changes and composer dependencies shouldn't affect it

Tested with Julius' docker, Viewer content is replaced:
image

**Comment by szaimen** [comment]
@Antreesy since you were able to test this, can you approve or is something missing from your Pov?

**Review by Antreesy — APPROVED** [review]
Rebased, recompiled, adjusted wording to user-insensitive: `To view a shared PDF file, the download needs to be allowed for this file share`

File: src/views/PDFView.vue (hunk 1 above)
Comment (Antreesy) [reply src/views/PDFView.vue]: This PR covers all shares (with users, guests, oublic links), where download is disabled.

For guests accounts + shareswith enabled download, it returns 500 Server error, which is correct, and not to be handled by PDF Viewer.
Instead, this app should be whitelisted in admin settings. Issue is tracked here: https://github.com/nextcloud/guests/issues/1249

**Comment by szaimen** [comment]
Thanks @Antreesy ☺️
